name: Django deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v4
        run: |
          source /home/wiinsboo/virtualenv/wagtail_demo/3.11/bin/activate && cd /home/wiinsboo/wagtail_demo